config/routes.rb
Risk2210::Application.routes.draw do

  ## Sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :create_session
  delete '/logout' => 'sessions#destroy', as: :logout

  ## Facebook Sessions
  get '/login/facebook' => redirect('/auth/facebook'), as: :facebook_authentication
  get '/auth/:provider/callback' => 'sessions#authenticate_facebook'
  get '/auth/failure' => 'sessions#failure'

  ## Change Password
  get "/account/password" => "passwords#edit", as: :edit_password
  patch "/account/password" => "passwords#update", as: :update_password

  ## Players
  resources :players

  ## Game Tracker
  resources :games, only: [:new, :create, :show, :destroy] do
    get :results, on: :member
  end

  ## Forums
  resources :forums, only: [:index, :show] do
    resources :topics, only: [:show, :create] do
      resources :comments, only: [:create, :edit, :update]
    end
  end

  ## Messages
  get "/messages/new", to: "messages#new", as: :new_message
  post "/messages/new", to: "messages#create", as: :create_message
  get "/messages(/:filter)", to: "messages#index", as: :messages

  ## Forgot Password
  get "/forgot-password" => "password_reset#index", as: :forgot_password
  post "/forgot-password" => "password_reset#create", as: :request_password_reset
  get "/reset-password/:token" => "password_reset#show", as: :find_password_reset
  put "/reset-password/:token" => "password_reset#update", as: :reset_password

  ## Expansions
  namespace :expansions do
    get "/" => "base#index", as: :index
    resources :factions, only: [:index, :show]
    get "/mars" => "maps#mars", as: :mars
    get "/io" => "maps#io", as: :io
    get "/europa" => "maps#europa", as: :europa
    get "/asteroid-colonies" => "maps#asteroid_colonies", as: :asteroid_colonies
    get "/pluto" => "maps#pluto", as: :pluto
    get "/arctic" => "maps#arctic", as: :arctic
    get "/titan" => "maps#titan", as: :titan
    get "/antarctica" => "maps#antarctica", as: :antarctica
    get "/tech-commander" => "commanders#tech", as: :tech_commander
    get "/resistance-commander" => "commanders#resistance", as: :resistance_commander
    get "/galaxy-commander" => "commanders#galaxy", as: :galaxy_commander
    get "/majors-promo-cards" => "commanders#majors_promo_cards", as: :majors_promo_cards
    get "/invasion-of-the-giant-amoebas" => "misc#amoebas", as: :amoebas
    get "/galactic-risk" => "misc#galactic", as: :galactic
    get "/dark-side-of-the-moon" => "maps#dark_side_moon", as: :dark_side_moon
    get "/capitals" => "misc#capitals", as: :capitals
  end

  ## Misc
  get "/about" => "pages#about", as: :about
  get "/resources" => "pages#resources", as: :resources

  ## API Endpoints
  scope "api/v1" do
    get "/factions" => "expansions/factions#index"
    get "/factions/:id" => "expansions/factions#show"
    get "/players" => "players#index"
    get "/players/:id" => "players#show"
    post "/turns" => "turns#create"
    put "/games/:id/:event" => "games#update"
  end

  ## Root
  root to: 'pages#home'

end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body,    type: String
  field :subject, type: String

  belongs_to :recipient, class_name: "Player", inverse_of: :messages, index: true
  belongs_to :sender, class_name: "Player", inverse_of: :sent_messages, index: true

  after_create :notify_recipient

  validates_presence_of :subject, :body, :recipient

private

  def notify_recipient
    PlayerMailer.message_notification(self).deliver_now
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :login_required

  def index
    if params[:filter].present? && params[:filter] == 'sent'
      self.active_tab = :sent
      @messages = current_player.sent_messages
    else
      self.active_tab = :inbox
      @messages = current_player.messages
    end
  end

  def new
    self.active_tab = :new_message
    if params[:recipient]
      recipient = Player.find(params[:recipient])
      @message = Message.new(recipient: recipient)
    else
      @message = Message.new
    end
  end

  def create
    self.active_tab = :new_message
    @message = current_player.sent_messages.build(message_params)
    if @message.save
      redirect_to messages_path, notice: "Message created!"
    else
      flash.now.alert = "There was an error saving your message"
      render action: :new
    end
  end

private

  def message_params
    params.require(:message).permit(:body, :subject, :recipient_id)
  end

end

app/views/messages/_nav.html.erb
<ul class="nav nav-tabs message-nav">
  <%= navigation_item("Inbox", messages_path, :inbox) %>
  <%= navigation_item("Sent Messages", messages_path(:sent), :sent) %>
  <%= navigation_item("New Message", new_message_path, :new_message) %>
</ul>

app/views/messages/index.html.erb
<div class="messages">
  <%= render partial: "messages/nav" %>
  <% if @messages.none? %>
    <p>You don't have any messages</p>
  <% end %>
  <% @messages.each do |message| %>
    <div class="panel panel-default message">
      <div class="panel-heading">
        <h3 class="panel-title"><%= message.subject %></h3>
      </div>
      <div class="panel-body">
        <div class="from">From: &nbsp;&nbsp;<%= link_to message.sender.name, player_path(message.sender) %></div>
        <div class="timestamp">Sent: &nbsp;&nbsp;&nbsp;<%= format_timestamp(message.created_at) %></div>
        <p class="body"><%= format_markdown(message.body) %></p>
      </div>
      <div class="panel-footer">
        <%= message_link(current_player, message.sender, "Reply") %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<div class="messages">
  <%= render partial: "messages/nav" %>

  <%= simple_form_for @message, url: create_message_path do |f| %>
    <%= error_messages_for @message %>
    <%= f.association :recipient, as: :select, collection: Player.all, label_method: :handle, value_method: :id %>
    <%= f.input :subject %>
    <%= f.input :body, as: :text, input_html: {rows: 10, cols: 100} %>
    <%= f.submit "Create Message", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
  <% end %>
</div>

<% content_for :sidebar do %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Formatting</h3>
    </div>
    <div class="panel-body">
      <p>
        The body of your message supports <a href='http://en.wikipedia.org/wiki/Markdown' target="_blank">Markdown</a> formatting.  Below are some syntax examples.
      </p>
      <%= render partial: "shared/markdown_examples" %>
    </div>
  </div>
<% end %>