config/routes.rb
Risk2210::Application.routes.draw do

  ## Sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :create_session
  delete '/logout' => 'sessions#destroy', as: :logout

  ## Facebook Sessions
  get '/login/facebook' => redirect('/auth/facebook'), as: :facebook_authentication
  get '/auth/:provider/callback' => 'sessions#authenticate_facebook'
  get '/auth/failure' => 'sessions#failure'

  ## Change Password
  get "/account/password" => "passwords#edit", as: :edit_password
  patch "/account/password" => "passwords#update", as: :update_password

  ## Players
  resources :players

  ## Game Tracker
  resources :games, only: [:new, :create, :show, :destroy] do
    get :results, on: :member
  end

  ## Forums
  resources :forums, only: [:index, :show] do
    resources :topics, only: [:show, :create] do
      resources :comments, only: [:create, :edit, :update]
    end
  end

  ## Messages
  get "/messages/new", to: "messages#new", as: :new_message
  post "/messages/new", to: "messages#create", as: :create_message
  get "/messages(/:filter)", to: "messages#index", as: :messages

  ## Forgot Password
  get "/forgot-password" => "password_reset#index", as: :forgot_password
  post "/forgot-password" => "password_reset#create", as: :request_password_reset
  get "/reset-password/:token" => "password_reset#show", as: :find_password_reset
  put "/reset-password/:token" => "password_reset#update", as: :reset_password

  ## Expansions
  namespace :expansions do
    get "/" => "base#index", as: :index
    resources :factions, only: [:index, :show]
    get "/mars" => "maps#mars", as: :mars
    get "/io" => "maps#io", as: :io
    get "/europa" => "maps#europa", as: :europa
    get "/asteroid-colonies" => "maps#asteroid_colonies", as: :asteroid_colonies
    get "/pluto" => "maps#pluto", as: :pluto
    get "/arctic" => "maps#arctic", as: :arctic
    get "/titan" => "maps#titan", as: :titan
    get "/antarctica" => "maps#antarctica", as: :antarctica
    get "/tech-commander" => "commanders#tech", as: :tech_commander
    get "/resistance-commander" => "commanders#resistance", as: :resistance_commander
    get "/galaxy-commander" => "commanders#galaxy", as: :galaxy_commander
    get "/majors-promo-cards" => "commanders#majors_promo_cards", as: :majors_promo_cards
    get "/invasion-of-the-giant-amoebas" => "misc#amoebas", as: :amoebas
    get "/galactic-risk" => "misc#galactic", as: :galactic
    get "/dark-side-of-the-moon" => "maps#dark_side_moon", as: :dark_side_moon
    get "/capitals" => "misc#capitals", as: :capitals
  end

  ## Misc
  get "/about" => "pages#about", as: :about
  get "/resources" => "pages#resources", as: :resources

  ## API Endpoints
  scope "api/v1" do
    get "/factions" => "expansions/factions#index"
    get "/factions/:id" => "expansions/factions#show"
    get "/players" => "players#index"
    get "/players/:id" => "players#show"
    post "/turns" => "turns#create"
    put "/games/:id/:event" => "games#update"
  end

  ## Root
  root to: 'pages#home'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to :player, index: true
  belongs_to :commentable, polymorphic: true, index: true
  has_many :comments, as: :commentable, dependent: :destroy

  after_create :update_topic_stats
  after_destroy :decrement_comment_counter

  validates_presence_of :body

  def topic
    parent = commentable
    loop do
      return parent if parent.is_a?(Topic) || parent.is_a?(NilClass)
      parent = parent.commentable
    end
  end

  def commentable_label
    "Comment - #{body.truncate(30)}"
  end

private

  def update_topic_stats
    return if topic.nil?
    topic.inc(comment_count: 1)
    topic.update_attribute(:last_comment_at, Time.now)
  end

  def decrement_comment_counter
    topic.inc(comment_count: -1)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  active_tab :forums

  before_action :find_forum
  before_action :find_topic
  before_action :login_required

  def create
    if params[:comment_parent_id].present?
      parent = Comment.find(params[:comment_parent_id])
    else
      parent = @topic
    end

    @comment = parent.comments.build(comment_params)
    @comment.player = current_player
    if @comment.save
      redirect_to forum_topic_path(@forum, @topic), notice: "Thanks for posting!"
    else
      @comments = @topic.comments.all
      flash.now.alert = "You can't post blank comments!"
      render template: "topics/show"
    end
  end

  def edit
    @comment = current_player.comments.find(params[:id])
    raise Mongoid::Errors::DocumentNotFound.new(Comment, params[:id], params[:id]) if @comment.nil?
  end

  def update
    @comment = current_player.comments.find(params[:id])
    raise Mongoid::Errors::DocumentNotFound.new(Comment, params[:id], params[:id]) if @comment.nil?
    if @comment.update_attributes(comment_params)
      redirect_to forum_topic_path(@forum, @topic), notice: "Successfully updated your comment."
    else
      flash.now.alert = "You can't post blank comments!"
      render action: :edit
    end
  end

private

  def find_forum
    @forum = Forum.find(params[:forum_id])
  end

  def find_topic
    @topic = Topic.find(params[:topic_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :topic_id)
  end

end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= avatar(comment.player, size: :normal) %>
  <%= edit_comment_link(@forum, @topic, comment) %>
  <%= link_to "Player: #{comment.player.handle}", player_path(comment.player), class: "profile-link" %>
  <br />
  <div class="timestamp">Posted: <%= format_timestamp(comment.created_at) %></div>
  <p class="body">
    <%= format_markdown(comment.body) %>
  </p>
  <a href='#' class='nested_comment_link btn btn-primary'><i class='icon-comment'></i> Reply to this comment</a>
  <div class="comment_form_container" style="display: none;">
    <%= render partial: "comments/form", locals: {parent_id: comment.id} %>
  </div>
</div>
<div class="nested-comments">
  <%= render partial: "comments/comment", collection: comment.comments.asc(:created_at) %>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <% if current_player %>
    <%= simple_form_for :comment, url: forum_topic_comments_path(@forum, @topic, comment_parent_id: parent_id), html: {class: 'form-vertical'} do |f| %>
      <%= f.input :body, as: :text, label: false, input_html: {class: 'comment-text'} %>
      <%= f.submit "Comment", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', players_path, class: 'btn btn-default nested-comment-cancel-button' %>
    <% end %>
  <% else %>
    <a data-toggle="modal" href="#login-modal" class="btn btn-primary">Login to comment</a>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div id="topic" class="well">
  <h2>Edit Comment</h2>
  <div class="comment-form">
    <%= simple_form_for @comment, url: forum_topic_comment_path(@forum, @topic, @comment), html: {class: 'form-vertical'} do |f| %>
      <%= f.input :body, as: :text, label: false, input_html: {class: 'comment-text'} %>
      <%= f.submit "Update", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', forum_topic_path(@forum, @topic), class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render partial: "shared/markdown_examples" %>
<% end %>