config/routes.rb
Risk2210::Application.routes.draw do

  ## Sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :create_session
  delete '/logout' => 'sessions#destroy', as: :logout

  ## Facebook Sessions
  get '/login/facebook' => redirect('/auth/facebook'), as: :facebook_authentication
  get '/auth/:provider/callback' => 'sessions#authenticate_facebook'
  get '/auth/failure' => 'sessions#failure'

  ## Change Password
  get "/account/password" => "passwords#edit", as: :edit_password
  patch "/account/password" => "passwords#update", as: :update_password

  ## Players
  resources :players

  ## Game Tracker
  resources :games, only: [:new, :create, :show, :destroy] do
    get :results, on: :member
  end

  ## Forums
  resources :forums, only: [:index, :show] do
    resources :topics, only: [:show, :create] do
      resources :comments, only: [:create, :edit, :update]
    end
  end

  ## Messages
  get "/messages/new", to: "messages#new", as: :new_message
  post "/messages/new", to: "messages#create", as: :create_message
  get "/messages(/:filter)", to: "messages#index", as: :messages

  ## Forgot Password
  get "/forgot-password" => "password_reset#index", as: :forgot_password
  post "/forgot-password" => "password_reset#create", as: :request_password_reset
  get "/reset-password/:token" => "password_reset#show", as: :find_password_reset
  put "/reset-password/:token" => "password_reset#update", as: :reset_password

  ## Expansions
  namespace :expansions do
    get "/" => "base#index", as: :index
    resources :factions, only: [:index, :show]
    get "/mars" => "maps#mars", as: :mars
    get "/io" => "maps#io", as: :io
    get "/europa" => "maps#europa", as: :europa
    get "/asteroid-colonies" => "maps#asteroid_colonies", as: :asteroid_colonies
    get "/pluto" => "maps#pluto", as: :pluto
    get "/arctic" => "maps#arctic", as: :arctic
    get "/titan" => "maps#titan", as: :titan
    get "/antarctica" => "maps#antarctica", as: :antarctica
    get "/tech-commander" => "commanders#tech", as: :tech_commander
    get "/resistance-commander" => "commanders#resistance", as: :resistance_commander
    get "/galaxy-commander" => "commanders#galaxy", as: :galaxy_commander
    get "/majors-promo-cards" => "commanders#majors_promo_cards", as: :majors_promo_cards
    get "/invasion-of-the-giant-amoebas" => "misc#amoebas", as: :amoebas
    get "/galactic-risk" => "misc#galactic", as: :galactic
    get "/dark-side-of-the-moon" => "maps#dark_side_moon", as: :dark_side_moon
    get "/capitals" => "misc#capitals", as: :capitals
  end

  ## Misc
  get "/about" => "pages#about", as: :about
  get "/resources" => "pages#resources", as: :resources

  ## API Endpoints
  scope "api/v1" do
    get "/factions" => "expansions/factions#index"
    get "/factions/:id" => "expansions/factions#show"
    get "/players" => "players#index"
    get "/players/:id" => "players#show"
    post "/turns" => "turns#create"
    put "/games/:id/:event" => "games#update"
  end

  ## Root
  root to: 'pages#home'

end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :subject, type: String
  field :view_count, type: Integer, default: 1
  field :comment_count, type: Integer, default: 0
  field :last_comment_at, type: DateTime

  slug :subject

  belongs_to :player, index: true
  belongs_to :forum, index: true
  has_many :comments, as: :commentable, dependent: :destroy, autosave: true

  validates_presence_of :subject

  accepts_nested_attributes_for :comments

  def increment_view_counter
    inc(view_count: 1)
  end

  def commentable_label
    "Topic - #{comments.first.body.truncate(30)}"
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  active_tab :forums

  before_action :find_forum
  before_action :find_topic, only: [:show]
  before_action :login_required, only: [:create]

  def show
    unless topics_viewed.include?(@topic.id)
      @topic.increment_view_counter
      topics_viewed << @topic.id
    end
    @comments = @topic.comments.asc(:created_at)
  end

  def create
    @topic = @forum.topics.build(topic_params)
    @topic.player = current_player
    @topic.comments.first.player = current_player

    if @topic.save
      topics_viewed << @topic.id
      redirect_to forum_topic_path(@forum, @topic), notice: "Thanks for posting!"
    else
      @topics = @forum.topics.all
      flash.now.alert = "There was an creating your topic."
      render template: "forums/show"
    end
  end

private

  def find_forum
    @forum = Forum.find(params[:forum_id])
  end

  def find_topic
    @topic = Topic.find(params[:id])
    raise Mongoid::Errors::DocumentNotFound.new(Topic, params[:id], params[:id]) if @topic.nil?
  end

  def topics_viewed
    session[:topics_viewed] ||= []
  end

  def topic_params
    params.require(:topic).permit(:subject, comments_attributes: [:body])
  end

end

app/views/topics/_comment.html.erb
<div class="well comment" >
  <%= image_tag(comment.player.profile_image_path(:square)) %>
  <%= link_to "Player: #{comment.player.handle}", player_path(comment.player), class: "profile-link" %>
  <br />
  <div class="timestamp">Posted: <%= format_timestamp(comment.created_at) %></div>
  <p class="body">
    <%= format_markdown(comment.body) %>
  </p>
  <a href='#' class='nested_comment_link btn btn-inverse'><i class='icon-comment icon-white'></i> Reply to this comment</a>
  <div class="comment_form_container" style="display: none;">
    <%= render :partial => "topics/comment_form", :locals => {:parent_id => comment.id} %>
  </div>
</div>
<div class="nested-comments">
  <%= render :partial => "topics/comment", :collection => comment.comments %>
</div>

app/views/topics/_comment_form.html.erb
<div class="comment-form">
  <% if logged_in? %>
    <% parent_id ||= nil %>
    <%= simple_form_for @comment, url: create_comment_forum_topic_path(@forum, @topic, comment_parent_id: parent_id), html: {class: 'form-vertical'} do |f| %>
      <%= error_messages_for @comment %>
      <%= f.input :body, as: :text, label: false, input_html: {class: 'comment-text'} %>
      <%= f.submit "Comment", class: 'btn btn-primary' %>
      <% if !defined?(hide_cancel) || defined?(hide_cancel) && hide_cancel != true %>
        <%= link_to 'Cancel', players_path, class: 'btn nested_comment_cancel_button' %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to "Login to comment", login_path %>
  <% end %>
</div>

app/views/topics/show.html.erb
<% content_for :page_title, "#{@topic.subject} | #{@forum.name}" %>
<div id="topic">
  <h1><%= @topic.subject %></h1>
  <%= render partial: "comments/comment", collection: @comments %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Reply (Top Level)</h3>
    </div>
    <div class="panel-body">
      <div class="comment-form">
        <% if current_player %>
          <%= simple_form_for :comment, url: forum_topic_comments_path(@forum, @topic), html: {class: 'form-vertical'} do |f| %>
            <%= f.input :body, as: :text, label: false, input_html: {class: 'comment-text'} %>
            <%= f.submit "Comment", class: 'btn btn-primary' %>
          <% end %>
        <% else %>
          <%= link_to "Login to comment", login_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
  <%= render partial: "forums/comment_formatting" %>
<% end %>