config/routes.rb
Risk2210::Application.routes.draw do

  ## Sessions
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :create_session
  delete '/logout' => 'sessions#destroy', as: :logout

  ## Facebook Sessions
  get '/login/facebook' => redirect('/auth/facebook'), as: :facebook_authentication
  get '/auth/:provider/callback' => 'sessions#authenticate_facebook'
  get '/auth/failure' => 'sessions#failure'

  ## Change Password
  get "/account/password" => "passwords#edit", as: :edit_password
  patch "/account/password" => "passwords#update", as: :update_password

  ## Players
  resources :players

  ## Game Tracker
  resources :games, only: [:new, :create, :show, :destroy] do
    get :results, on: :member
  end

  ## Forums
  resources :forums, only: [:index, :show] do
    resources :topics, only: [:show, :create] do
      resources :comments, only: [:create, :edit, :update]
    end
  end

  ## Messages
  get "/messages/new", to: "messages#new", as: :new_message
  post "/messages/new", to: "messages#create", as: :create_message
  get "/messages(/:filter)", to: "messages#index", as: :messages

  ## Forgot Password
  get "/forgot-password" => "password_reset#index", as: :forgot_password
  post "/forgot-password" => "password_reset#create", as: :request_password_reset
  get "/reset-password/:token" => "password_reset#show", as: :find_password_reset
  put "/reset-password/:token" => "password_reset#update", as: :reset_password

  ## Expansions
  namespace :expansions do
    get "/" => "base#index", as: :index
    resources :factions, only: [:index, :show]
    get "/mars" => "maps#mars", as: :mars
    get "/io" => "maps#io", as: :io
    get "/europa" => "maps#europa", as: :europa
    get "/asteroid-colonies" => "maps#asteroid_colonies", as: :asteroid_colonies
    get "/pluto" => "maps#pluto", as: :pluto
    get "/arctic" => "maps#arctic", as: :arctic
    get "/titan" => "maps#titan", as: :titan
    get "/antarctica" => "maps#antarctica", as: :antarctica
    get "/tech-commander" => "commanders#tech", as: :tech_commander
    get "/resistance-commander" => "commanders#resistance", as: :resistance_commander
    get "/galaxy-commander" => "commanders#galaxy", as: :galaxy_commander
    get "/majors-promo-cards" => "commanders#majors_promo_cards", as: :majors_promo_cards
    get "/invasion-of-the-giant-amoebas" => "misc#amoebas", as: :amoebas
    get "/galactic-risk" => "misc#galactic", as: :galactic
    get "/dark-side-of-the-moon" => "maps#dark_side_moon", as: :dark_side_moon
    get "/capitals" => "misc#capitals", as: :capitals
  end

  ## Misc
  get "/about" => "pages#about", as: :about
  get "/resources" => "pages#resources", as: :resources

  ## API Endpoints
  scope "api/v1" do
    get "/factions" => "expansions/factions#index"
    get "/factions/:id" => "expansions/factions#show"
    get "/players" => "players#index"
    get "/players/:id" => "players#show"
    post "/turns" => "turns#create"
    put "/games/:id/:event" => "games#update"
  end

  ## Root
  root to: 'pages#home'

end

app/models/player.rb
class Player
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Geocoder::Model::Mongoid

  module ImageSource
    Facebook = "Facebook"
    Gravatar = "Gravatar"
  end

  FIFTY_MILES = (69 / 50)

  ## Field Definitions
  field :provider, type: String
  field :uid, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :handle, type: String
  field :city, type: String
  field :state, type: String
  field :zip_code, type: String
  field :bio, type: String
  field :website, type: String
  field :facebook_image_url, type: String
  field :image_source, type: String
  field :gravatar_hash, type: String
  field :public_profile, type: Boolean, default: true
  field :password_digest, type: String
  field :remember_me_token, type: String
  field :raw_authorization, type: Hash
  field :login_count, type: Integer, default: 1
  field :last_login_at, type: DateTime, default: -> { Time.now }
  field :favorite_color, type: String
  field :password_reset_token, type: String
  field :admin, type: Boolean, default: false
  field :coordinates, type: Array

  ## Associations
  has_many :topics, dependent: :destroy, autosave: true
  has_many :comments, dependent: :destroy, autosave: true
  has_many :game_players
  has_many :games, inverse_of: :creator, dependent: :destroy
  has_many :messages, inverse_of: :recipient
  has_many :sent_messages, inverse_of: :sender, class_name: "Message"

  ## Plugins
  slug :handle
  geocoded_by :location

  ## Indexes
  index({handle: 1, email: 1, uuid: 1}, {unique: true})
  index(zip_code: 1, city: 1, state: 1)
  index({ coordinates: "2dsphere" }, { min: -1000, max: 1000} )

  attr_reader :password

  ## Callbacks
  before_save :generate_gravatar_hash
  after_create :deliver_welcome_email
  after_create :link_game_players
  before_save :geocode, if: ->(player) { player.location.present? && (player.zip_code_changed? || player.city_changed? || player.state_changed?) }

  ## Validations
  validates_presence_of :email, :handle
  validates_uniqueness_of :email, :handle
  validates_inclusion_of :image_source, in: [ImageSource::Facebook, ImageSource::Gravatar], allow_blank: true
  validates_format_of :email, with: EmailAddressValidation::EMAIL_ADDRESS_EXACT_PATTERN, allow_blank: true
  validates_confirmation_of :password
  validates_presence_of :password_digest, if: ->(player) { player.uid.blank? }
  validates_inclusion_of :favorite_color, in: GamePlayer::COLORS, allow_blank: true

  ## Scopes
  scope :public_profiles, ->() { where(public_profile: true).asc(:created_at) }
  scope :nearby, ->(coordinates) { geo_near(coordinates).max_distance(FIFTY_MILES) }

  ## Facebook image size options
  ## square=50x50, small=50xVariable, normal=100xVariable, large=200xVariable
  def profile_image_path(size=:normal)
    default_avatar_path = "https://risk2210.net/assets/default_avatar.png"
    if image_source == ImageSource::Facebook && facebook_image_url
      return facebook_image_url.gsub("http://", "https://") + "?type=#{size}"
    elsif image_source == ImageSource::Gravatar
      gravatar_size = case size
        when :square, :small ; 50
        when :normal ; 100
        when :large ; 200
      end
      return "https://www.gravatar.com/avatar/#{gravatar_hash}?size=#{gravatar_size}&default=#{CGI::escape(default_avatar_path)}"
    else
      return default_avatar_path
    end
  end

  def change_password(password_attributes={}, options={})
    validate_old_password = options.fetch(:validate_old_password, true)
    if password_digest.present? && validate_old_password && !valid_password?(password_attributes.delete(:old_password))
      errors.add(:base, "Old password doesn't match")
      return false
    elsif password_attributes[:password].blank?
      errors.add(:password, "Password can't be blank")
      return false
    else
      return update_attributes(password_attributes)
    end
  end

  def location
    @location ||= begin
      @location = ""
      @location = city if city.present?
      @location = "#{@location}, " if city.present? && state.present?
      @location = "#{@location}#{state}" if state.present?
      @location = "#{@location} #{zip_code}" if zip_code.present?
      @location
    end
  end

  def password=(unencrypted_password)
    @password = unencrypted_password
    unless unencrypted_password.blank?
      self.password_digest = BCrypt::Password.create(unencrypted_password, cost: Rails.configuration.password_cost)
    end
  end

  def set_login_stats
    self.login_count   = self.login_count + 1
    self.last_login_at = Time.now
  end

  def valid_password?(unencrypted_password)
    password_digest.present? && BCrypt::Password.new(password_digest) == unencrypted_password
  end

  def request_password_reset!
    self.password_reset_token = SecureRandom.hex(8)
    self.save
    PlayerMailer.password_reset(self).deliver_now
  end

  def name
    @name ||= begin
      if first_name.present? || last_name.present?
        [first_name, last_name].compact.join(" ")
      else
        slug
      end
    end
  end

private

  def generate_gravatar_hash
    if email.present? && email_changed?
      self.gravatar_hash = Digest::MD5.hexdigest(email)
    end
  end

  def deliver_welcome_email
    PlayerMailer.welcome_email(self).deliver_now
  end

  def link_game_players
    GamePlayer.where(handle: handle).each do |game_player|
      game_player.update_attribute(:player_id, self.id)
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :login_required, only: [:edit, :update, :destroy]
  before_action :find_player, only: [:show, :edit, :update, :destroy]
  before_action :authorize_current_player, only: [:edit, :update, :destroy]

  active_tab :players

  def index
    @players = Player.public_profiles
  end

  def show
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      login(@player, redirect_to: edit_player_path(@player), notice: "Thanks for registering! Please fill out your profile.")
    else
      flash.now.alert = "There was an error creating your account."
      render action: :new
    end
  end

  def edit
  end

  def update
    if @player.update_attributes(player_params)
      redirect_to player_path(@player), notice: "Thanks for updating your profile!"
    else
      flash.now.alert = "There was an error updating your profile."
      render action: :edit
    end
  end

  def destroy
    @player.destroy
    logout
    redirect_to root_path, notice: "Your account has been removed. Sorry to see you go. :("
  end

private

  def find_player
    @player = Player.find(params[:id])
    raise Mongoid::Errors::DocumentNotFound.new(Player, params[:id], params[:id]) if @player.nil?
  end

  def authorize_current_player
    if current_player != @player
      redirect_to root_path, alert: "Unauthorized!"
    end
  end

  def player_params
    params.require(:player).permit(:email, :first_name, :last_name, :handle, :city, :state, :zip_code, :bio, :website, :image_source, :public_profile, :password, :password_confirmation, :old_password, :favorite_color)
  end

end

app/helpers/players_helper.rb
module PlayersHelper

  def us_states_options
    States::STATES
  end

  def avatar(player, size: :large)
    image_path = player.profile_image_path(size)

    pixels = size == :large ? 170 : 50
    return image_tag(image_path, width: "#{pixels}px;", alt: player.handle, class: "img-rounded")
  end

  def nearby_players(current_player)
    return if current_player.nil?
    if current_player.coordinates.nil? || current_player.coordinates.empty?
      nearby_players = []
    else
      begin
        nearby_players = Player.nearby(current_player.coordinates).to_a.except(current_player)
      rescue Exception => exception
        nearby_players = []
      end
    end
    render partial: "players/nearby_players", locals: {nearby_players: nearby_players, current_player: current_player}
  end

  def message_link(current_player, player, label="Message")
    return if current_player.nil?
    return link_to(content_tag(:i, "", class: "fa fa-envelope") + " #{label}", new_message_path(recipient: player.slug), class: "btn btn-xs btn-info")
  end

end

app/views/players/_nearby_players.html.erb
<div class="panel panel-primary nearby-players">
  <div class="panel-heading">
    <h3 class="panel-title">Nearby Players</h3>
  </div>
  <div class="panel-body">
    <% if current_player.location.blank? %>
      <p>Update the location settings on your <%= link_to "profile", edit_player_path(current_player) %> to see nearby Risk 2210 players.</p>
    <% else %>
      <p>(within 50 miles of <%= current_player.location %>)</p>
      <% if nearby_players.size > 0 %>
        <table class="table table-bordered table-striped">
          <% nearby_players.each do |player| %>
            <tr>
              <td>
                <%= link_to(player.slug, player_path(player)) %>
              </td>
              <td>
                <%= message_link(current_player, player) %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>Sorry, there are no other Risk 2210 players nearby.</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/players/edit.html.erb
<% content_for :page_title, "Edit Profile" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Player Profile</h3>
  </div>
  <div class="panel-body">
    <%= simple_form_for @player do |f| %>
      <%= error_messages_for @player %>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :email %>
          <%= f.input :handle %>
          <%= f.input :favorite_color, collection: GamePlayer::COLORS %>
        </div>
        <div class="col-md-6">
          <%= f.input :city %>
          <%= f.input :state, collection: us_states_options %>
          <%= f.input :zip_code %>
          <%= f.input :image_source, collection: [Player::ImageSource::Facebook, Player::ImageSource::Gravatar], as: :radio_buttons, label: "Profile Image Source" %>
          <%= f.input :public_profile, as: :boolean %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :website %>
          <%= f.input :bio, as: :text, input_html: {class: 'span6', rows: 10} %>
        </div>
      </div>
      <%= f.submit "Update Profile", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', players_path, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<% content_for :sidebar do %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Profile Image Source</h3>
    </div>
    <div class="panel-body">
      If you registered via Facebook your Facebook profile image will be available for use.  You can also setup a free <a href='http://www.gravatar.com' target="_blank">Gravatar</a> account and choose that as your profile image.
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Public Profile</h3>
    </div>
    <div class="panel-body">
      If the public profile checkbox is unchecked, your profile won't be listed on the site.
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Bio</h3>
    </div>
    <div class="panel-body">
      <p>
        You can use <a href='http://en.wikipedia.org/wiki/Markdown' target="_blank">Markdown</a> formatting in your bio.  Below are some syntax examples.
      </p>
      <%= render partial: "shared/markdown_examples" %>
    </div>
  </div>

  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">Remove Account</h3>
    </div>
    <div class="panel-body">
      We hate to see you go. If you must, press the red button. All your data will be permanently removed and you will never hear from us again.
    </div>
    <div class="panel-footer">
      <%= link_to  player_path(@player), class: "btn btn-danger", data: {confirm: "Are you sure you want to remove your account?", method: :delete} do %>
        <i class='fa fa-trash icon-white'></i> Remove Account
      <% end %>
    </div>
  </div>

<% end %>

app/views/players/index.html.erb
<div class="table-wrapper">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Handle</th>
        <th>Location</th>
        <th>Games Played</th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= link_to player.handle, player_path(player) %></td>
          <td><%= player.location %></td>
          <td><%= player.game_players.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% content_for :sidebar do %>
  <%= nearby_players(current_player) %>
<% end %>

app/views/players/new.html.erb
<% content_for :page_title, "New Player" %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Player Account</h3>
  </div>
  <div class="panel-body">
    <%= simple_form_for @player do |f| %>
      <%= error_messages_for @player %>
        <%= f.input :email %>
        <%= f.input :handle %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.submit "Create Account", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<% content_for :page_title, "#{@player.handle} | Players" %>
<div id="player-profile">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @player.handle %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3">
          <%= avatar(@player, size: :large) %>
          <% if @player.website.present? %>
            <div class="site">
              <%= link_to @player.website, @player.website, target: "_blank" %>
            </div>
          <% end %>
          <div class="location">
            <%= @player.location %>
          </div>
        </div>
        <div class="col-md-9">
          <%= format_markdown(@player.bio) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 message-link">
          <%= message_link(current_player, @player) %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Games Played</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @player.game_players.map(&:game).each do |game| %>
        <% if game.completed? %>
          <li><%= link_to format_date(game.created_at), results_game_path(game) %></li>
        <% else %>
          <li><%= link_to format_date(game.created_at), game_path(game) %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<% end %>